import { VocabularyWord, Exercise, Unit, LessonNode } from '../types';

// The raw vocabulary list provided, compacted for efficiency.
// Format: Word (POS), Definition, Example Sentence;
const rawVocabulary = `Abacus (n), Frame with balls for calculating, She used an abacus to teach children basic arithmetic;
Abate (v), To lessen or subside, The storm began to abate after midnight;
Abdication (n), Giving up control or authority, The king's abdication shocked the nation;
Aberration (n), Straying away from normal, His rude behavior was an aberration from his usual kindness;
Abet (v), Help or encourage wrongdoing, She refused to abet his illegal scheme;
Abeyance (n), Suspended action, The project was held in abeyance until funding arrived;
Abhor (v), To hate or detest, I abhor violence in all its forms;
Abide (v), To be faithful or endure, We must abide by the rules of the game;
Abjure (v), Promise to give up, He abjured his former beliefs and started anew;
Abraded (adj), Rubbed off or worn away, The abraded surface of the rock was smooth to touch;
Abrogate (v), Repeal or annul by authority, The government decided to abrogate the outdated law;
Abscond (v), Go away suddenly to avoid arrest, The thief absconded with the stolen jewelry;
Abstruse (adj), Difficult to comprehend, The professor's abstruse theory confused most students;
Abut (v), Border on, Our property abuts the national park;
Abysmal (adj), Bottomless or extremely bad, The team's performance was abysmal this season;
Acarpous (adj), Sterile or no longer fertile, The acarpous soil yielded no crops;
Acclaimed (adj), Welcomed with approval, The acclaimed author won another literary prize;
Accolade (n), Praise or approval, She received accolades for her outstanding performance;
Accretion (n), Growing of separate things into one, The accretion of dust made the shelf dirty;
Adamant (adj), Inflexible or unchangeable, She was adamant about finishing the project on time;
Admonitory (adj), Containing warning, The teacher gave an admonitory look to the noisy students;
Adorn (v), Add beauty or decorate, She adorned the room with fresh flowers;
Adulteration (n), Making impure or poorer quality, The adulteration of food products is illegal;
Affable (adj), Polite and friendly, The affable host made everyone feel welcome;
Affinity (n), Close connection or relationship, She has an affinity for classical music;
Aggravate (v), Make worse or irritate, His comments only aggravated the situation;
Agile (adj), Active or quick moving, The agile gymnast performed impressive flips;
Agog (adj), Eager or excited, The children were agog with anticipation for Christmas;
Ail (v), Trouble or be ill, What ails you today? You seem unwell;
Alacrity (n), Eager and cheerful readiness, She accepted the challenge with alacrity;
Alcove (n), Recess or partially enclosed place, We placed a reading chair in the alcove;
Allegiance (n), Duty or loyalty, Citizens pledge allegiance to their country;
Alleviate (v), Make pain easier to bear, The medicine helped alleviate her headache;
Alloy (v), Mix with something inferior, They alloyed the gold with cheaper metals;
Aloof (adj), Reserved or indifferent, He remained aloof from office politics;
Amalgamate (v), Mix or combine, The two companies decided to amalgamate;
Ambidextrous (adj), Using both hands equally well, The ambidextrous artist could paint with either hand;
Ambiguous (adj), Doubtful or uncertain, His ambiguous response left us confused;
Ambivalent (adj), Having two contrary feelings, She felt ambivalent about moving to a new city;
Ameliorate (v), Improve or make better, New policies helped ameliorate working conditions;
Amortize (v), End debt by setting aside money, They amortized the loan over ten years;
Anguish (n), Severe suffering, The loss filled her with anguish;
Animosity (n), Strong dislike, There was animosity between the rival teams;
Antidote (n), Medicine against poison, The doctor administered an antidote immediately;
Antithetical (adj), Directly opposing, His actions were antithetical to his words;
Apartheid (n), Brutal racial discrimination, Apartheid ended in South Africa in 1994;
Aplomb (n), Self-confidence, She handled the crisis with aplomb;
Apostate (n), One who abandons beliefs, He was branded an apostate by his former group;
Apotheosis (n), Glorification to godliness, The statue represents the apotheosis of the hero;
Appease (v), Make quiet or calm, They tried to appease the angry crowd;
Apprehensive (adj), Fearful about future, She felt apprehensive before the exam;
Apprise (v), Give notice or inform, Please apprise me of any changes;
Approbation (n), Approval, His work received widespread approbation;
Apropos (adj), Appropriate to the situation, Your comment was quite apropos;
Apt (adj), Well-suited or quick-witted, She gave an apt response to the question;
Arabesque (n), Complex ornate design, The ceiling featured beautiful arabesques;
Arboreal (adj), Of or connected with trees, Monkeys are arboreal creatures;
Ardor (n), Enthusiasm, He pursued his goals with great ardor;
Arduous (adj), Steep or difficult, The arduous climb exhausted the hikers;
Argot (n), Jargon or slang, Criminals often use their own argot;
Arrant (adj), In the highest degree, He told an arrant lie;
Arrogance (n), Proud superior manner, His arrogance made him unpopular;
Articulate (v), Speak distinctly, She can articulate her thoughts clearly;
Ascend (v), Go or come up, We watched the balloon ascend into the sky;
Ascertain (v), Get to know, We need to ascertain the facts first;
Ascetic (adj), Practicing self-denial, The monk lived an ascetic lifestyle;
Ascribe (v), Consider to be the origin of, She ascribed her success to hard work;
Aseptic (adj), Surgically clean, The operating room must be aseptic;
Asperity (n), Roughness or harshness, He spoke with asperity when angry;
Aspersion (n), Slander, They cast aspersions on her character;
Assail (v), Attack violently, Critics assailed the new policy;
Assiduous (adj), Diligent or hard-working, Her assiduous efforts paid off;
Assuage (v), Make pain or desire less, Nothing could assuage his grief;
Asterisk (n), The mark used for omitted letters, An asterisk indicated a footnote;
Astringent (n), Substance that shrinks, The astringent helped close the wound;
Astute (adj), Clever or quick at seeing advantage, He made an astute business decision;
Atonement (n), Repayment or compensation, He sought atonement for his mistakes;
Attenuate (v), Make thin or weaken, The signal attenuated over distance;
Attune (v), Bring into harmony, She attuned herself to nature;
Audacious (adj), Daring or foolishly bold, His audacious plan surprised everyone;
Augury (n), Omen or sign, They saw the rainbow as a good augury;
August (adj), Majestic or venerable, The august assembly gathered for the ceremony;
Auspicious (adj), Favorable or successful, It was an auspicious beginning;
Austere (adj), Severely simple and plain, The room had austere furnishings;
Auxiliary (adj), Helping or supporting, We brought auxiliary supplies just in case;
Aver (v), Affirm or assert, He averred his innocence;
Aversion (n), Strong dislike, She has an aversion to spiders;
Avid (adj), Eager or greedy, He is an avid reader;
Avow (v), Admit or declare openly, She avowed her love for him;
Baleful (adj), Harmful or causing evil, He gave her a baleful look;
Balk (v), Purposely get in the way of, The horse balked at the jump;
Baneful (adj), Causing harm or ruin, The baneful effects of pollution were evident;
Barrage (n), Artificial obstacle built across river, The barrage controlled the water flow;
Barren (adj), Unable to have young ones, The barren land produced nothing;
Bask (v), Enjoy warmth and light, We basked in the sunshine;
Beatify (v), Bless or make happy, The Pope beatified the saint;
Bedizen (v), Adorn in a cheap showy manner, She bedizened herself with gaudy jewelry;
Belabor (v), Beat hard, Don't belabor the point;
Bellicose (adj), Belligerent or warlike, His bellicose attitude caused conflicts;
Belligerent (adj), Waging war, The belligerent nations finally agreed to peace;
Benefactor (n), Person who has given help, The anonymous benefactor donated generously;
Benevolence (n), Wish or activity in doing good, Her benevolence touched many lives;
Benign (adj), Kind and gentle, The doctor said the tumor was benign;
Bequest (n), Arrangement to give something at death, She left a bequest to charity;
Berate (v), Scold sharply, The coach berated the team for poor performance;
Bereft (adj), Robbed or dispossessed of something, She was bereft of hope;
Bewilder (v), Puzzle or confuse, The complex instructions bewildered him;
Bigot (n), Stubborn narrow-minded person, A bigot refuses to accept other views;
Bilge (n), Bulge or protuberance of cask, Water collected in the ship's bilge;
Blandishment (n), Flattery or coaxing, No amount of blandishment would change her mind;
Blandness (n), Comforting but uninteresting manner, The blandness of the meal disappointed us;
Blatant (adj), Noisy and rough, His blatant disregard for rules was shocking;
Blithe (adj), Cheerful or carefree, She had a blithe spirit;
Bogus (adj), Sham or not genuine, He was arrested for using bogus documents;
Boisterous (adj), Loud and rough, The boisterous children ran through the house;
Bolster (v), Give greatly needed support, Extra funding helped bolster the program;
Boorish (adj), Crude or rude, His boorish behavior embarrassed everyone;
Brash (adj), Hasty or cheeky, His brash comments offended many;
Brass (n), Yellow metal mixing copper and zinc, The band played brass instruments;
Brazen (adj), Made of brass or shameless, She made a brazen attempt to cheat;
Breach (n), Opening or broken place, The breach in the wall allowed entry;
Brittle (adj), Easily broken, The brittle glass shattered easily;
Broach (v), Bring up or begin to talk about, She broached the subject carefully;
Brook (v), To tolerate or endure, I will not brook such disrespect;
Buoyant (adj), Able to float or light-hearted, Her buoyant personality lifted everyone's spirits;
Burgeon (v), Grow forth or send out buds, The city's population began to burgeon;
Burnish (v), To polish or rub to shine, He burnished the silver until it gleamed;
Cabal (n), Scheme or group of plotters, A secret cabal plotted against the king;
Cadge (v), To beg or get by begging, He tried to cadge a free meal;
Cajole (v), Use flattery to persuade, She cajoled him into helping her;
Calipers (n), Metal supports or measuring instrument, The engineer used calipers to measure precisely;
Calumny (n), Slander, The politician sued for calumny;
Candid (adj), Frank or straightforward, I appreciate your candid opinion;
Cant (n), Insincere talk or jargon, His speech was full of political cant;
Cantankerous (adj), Bad-tempered or quarrelsome, The cantankerous old man complained constantly;
Canvass (v), Discuss thoroughly, They canvassed the neighborhood for votes;
Castigate (v), Chastise or punish, The editorial castigated the government's policy;
Castigation (n), Severe punishment, The criminal received public castigation;
Catalyst (n), Substance that causes speeding up, The scandal was a catalyst for reform;
Caustic (adj), Biting or sarcastic, Her caustic remarks hurt his feelings;
Censure (n), Expression of blame or rebuke, The senator faced censure from colleagues;
Centurion (n), Leader of unit of 100 soldiers, The centurion commanded his troops bravely;
Chary (adj), Cautious or wary, Be chary of strangers offering help;
Chastened (adj), Corrected or punished, The chastened child apologized;
Chastisement (n), Punishment, He received chastisement for his misdeeds;
Chauvinist (n), Blindly devoted patriot, The chauvinist refused to see any faults in his country;
Chicanery (n), Legal trickery or false argument, The lawyer's chicanery was exposed;
Chisel (n), Steel tool for shaping material, He used a chisel to carve the wood;
Churl (n), Bad-tempered person, Don't be such a churl;
Clamor (n), Shout or complain with noise, The crowd's clamor grew louder;
Clientele (n), Customers, The restaurant has a loyal clientele;
Clinch (v), Settle conclusively, They clinched the deal with a handshake;
Cling (v), Resist separation, The child clung to her mother;
Clot (n), Half-solid lump from liquid, A blood clot blocked the artery;
Cloture (n), Closing device to end debate, The senate voted for cloture;
Coagulation (n), Change to thick and solid state, Coagulation stops bleeding;
Coalescing (v), Coming together into one substance, The droplets were coalescing into larger drops;
Coax (v), Get somebody to do something by kindness, She coaxed the cat down from the tree;
Coda (n), Passage that completes music, The symphony ended with a beautiful coda;
Coddle (v), Treat with care and tenderness, Don't coddle the children too much;
Coerce (v), Compel or force, They tried to coerce him into signing;
Coeval (adj), Of the same period, The two civilizations were coeval;
Cogent (adj), Strong or convincing, She made a cogent argument;
Cogitate (v), Think deeply or meditate, He sat cogitating on the problem;
Cognizant (adj), Being fully aware of, She was cognizant of the risks;
Colander (n), Bowl with holes to drain water, Drain the pasta in a colander;
Collusion (n), Secret agreement for deceit, The companies were guilty of collusion;
Combustion (n), Process of burning, Combustion requires oxygen;
Commemorate (v), Keep the memory of, We commemorate the heroes annually;
Commodious (adj), Having plenty of space, The commodious house fit the large family;
Commuter (n), Person who travels regularly, The commuter takes the train daily;
Complaisance (n), Willingness to please, His complaisance made him easy to work with;
Compunction (n), Feeling of regret for action, He felt no compunction about lying;
Conceal (v), Hide or keep secret, She tried to conceal her disappointment;
Conceit (n), Too much pride, His conceit made him unbearable;
Conciliatory (adj), Reconciling or soothing, She adopted a conciliatory tone;
Concord (n), Agreement or harmony, The nations lived in concord;
Concur (v), Agree in opinion, I concur with your assessment;
Condense (v), Make more dense or laconic, Please condense your report;
Condone (v), Forgive, I cannot condone such behavior;
Congeal (v), Make or become stiff and solid, The blood congealed quickly;
Conjoin (v), Join together, The two rivers conjoin here;
Connoisseur (n), Person with good judgment, He is a connoisseur of fine wine;
Connotation (n), Suggestion in addition to meaning, The word has negative connotations;
Consequential (adj), Pompous or self-important, He gave a consequential speech;
Console (v), Give comfort or sympathy, She consoled the grieving family;
Conspicuous (adj), Easily seen or remarkable, He was conspicuous by his absence;
Consternation (n), Surprise and fear or dismay, The news caused consternation;
Constrain (v), Compel, Budget constraints limited our options;
Constrict (v), Make tight or smaller, The snake constricted its prey;
Consume (v), Get to the end of, Fire consumed the building;
Consummate (adj), Perfect or complete, He is a consummate professional;
Contemn (v), Scorn or despise, They contemned his cowardly actions;
Contentious (adj), Argumentative or quarrelsome, The contentious issue divided the group;
Contiguous (adj), Touching or neighboring, The two properties are contiguous;
Contrite (adj), Filled with sorrow for wrongdoing, He gave a contrite apology;
Contumacious (adj), Insubordinate or rebellious, The contumacious soldier was court-martialed;
Conundrum (n), Riddle or dilemma, The mystery presented a real conundrum;
Conviction (n), Convincing or firm belief, She spoke with conviction;
Convoke (v), Call together or summon, The king convoked his council;
Convoluted (adj), Complicated or twisted, The plot was too convoluted to follow;
Cordial (adj), Warm and sincere, We received a cordial welcome;
Cordon (n), Line of police acting as guard, Police formed a cordon around the area;
Cornucopia (n), Abundant supply, The market offered a cornucopia of fresh produce;
Corporeal (adj), Physical or of the body, Ghosts lack corporeal form;
Correlate (v), Have mutual relation, Height and weight often correlate;
Corroboration (n), Additional strengthening evidence, The witness provided corroboration;
Countenance (v), Favor or approve of, I cannot countenance such cruelty;
Counterfeit (adj), Forgery, The bill was counterfeit;
Countervail (v), Counterbalance, The benefits countervail the costs;
Covert (adj), Disguised or secret, They conducted covert operations;
Covetous (adj), Eagerly desirous, He cast covetous glances at her jewelry;
Cower (v), Crouch or shrink back, The dog cowered in fear;
Coy (adj), Shy or modest, She gave a coy smile;
Crass (adj), Very great stupidity, His crass ignorance was appalling;
Cravat (n), Piece of linen worn as necktie, He wore an elegant cravat;
Craven (adj), Cowardly, His craven behavior disappointed everyone;
Crease (n), Line made by crushing, Iron out the creases in the shirt;
Credulity (n), Too great readiness to believe, His credulity made him an easy target;
Credulous (adj), Ready to believe things, Don't be so credulous;
Crush (v), Press and lose shape, The box was crushed in shipping;
Cryptic (adj), Secret with hidden meaning, He left a cryptic message;
Cumbersome (adj), Burdensome or awkward to carry, The cumbersome package was hard to lift;
Curmudgeon (n), Bad-tempered person, The old curmudgeon never smiled;
Curriculum (n), Course of study, The school updated its curriculum;
Cursory (adj), Quick or hurried, He gave the document a cursory glance;
Curtail (v), Make shorter than planned, We had to curtail our vacation;
Dainty (adj), Pretty or delicate, She took dainty bites of cake;
Daunt (v), Intimidate or make fearful, Nothing could daunt her determination;
Dawdler (n), Person who is slow, Stop being such a dawdler;
Dearth (n), Shortage, There is a dearth of qualified candidates;
Debacle (n), Sudden disaster or overthrow, The project ended in debacle;
Decorum (n), Propriety or properness, Please observe proper decorum;
Decree (n), Order given by authority, The king issued a decree;
Decry (v), Disapprove of, Critics decried the new law;
Defer (v), Postpone or show respect, We deferred the decision until next week;
Deferential (adj), Showing respect, He was deferential to his elders;
Defiance (n), Open disobedience or resistance, She acted in defiance of orders;
Delineate (v), Portray or sketch out, Please delineate your plan clearly;
Deluge (n), Great flood or heavy rush, A deluge of emails arrived;
Demagogue (n), Person appealing not to reason, The demagogue stirred up the crowd;
Demur (v), Hesitate or raise objections, She demurred at the suggestion;
Denigrate (v), Blacken or belittle, Don't denigrate his achievements;
Denouement (n), Outcome or unraveling of plot, The story's denouement was surprising;
Deplete (v), Use until none remains, We depleted our supplies;
Deposition (n), Dethronement or depositing, The lawyer took the witness's deposition;
Deprave (v), Make morally bad or corrupt, Violence on TV can deprave young minds;
Deprecate (v), Protest against or disapprove, I deprecate such wasteful spending;
Dereliction (n), Deserting and leaving to ruin, His dereliction of duty was inexcusable;
Derision (n), Ridicule or mockery, His proposal met with derision;
Derivative (adj), Unoriginal or from another source, The work was derivative;
Derogatory (adj), Insulting or damaging, He made derogatory remarks;
Descry (v), Catch sight of, We could descry land in the distance;
Desiccant (n), Substance to absorb moisture, Put a desiccant packet in the container;
Desuetude (n), Cessation of use or disuse, The law fell into desuetude;
Desultory (adj), Aimless or at random, They made desultory conversation;
Deter (v), Discourage or hinder, Nothing will deter me from my goal;
Detraction (n), Slandering or verbal attack, His detraction of others was unseemly;
Detumescence (n), Lessening of swelling, Detumescence occurred after treatment;
Deviance (n), Being different in moral standards, Social deviance was not tolerated;
Dexterity (n), Skill in handling, The surgeon showed great dexterity;
Diaphanous (adj), Transparent or gauzy, She wore a diaphanous veil;
Diatribe (n), Bitter and violent verbal attack, He launched into a diatribe;
Diffidence (n), Shyness, Her diffidence held her back;
Dilate (v), Become wider or large, Her pupils dilated in the dark;
Disallow (v), Refuse to allow or accept, The judge disallowed the evidence;
Discern (v), See clearly with effort, I could discern a figure in the fog;
Discomfit (v), Confuse or embarrass, The question discomfited him;
Disconcert (v), Upset the self-possession of, His rude behavior disconcerted her;
Discountenance (v), Refuse to approve of, She discountenanced such frivolity;
Discourse (n), Speech or lecture, The professor gave a lengthy discourse;
Discredit (v), Refuse to believe, The scandal discredited him;
Discreet (adj), Careful or prudent, Please be discreet about this matter;
Discrete (adj), Individually distinct, The book has three discrete sections;
Disdain (n), Look on with contempt, He regarded the offer with disdain;
Disencumber (v), Free from encumbrance, She disencumbered herself of unnecessary baggage;
Disheveled (adj), Untidy, Her hair was disheveled;
Disingenuous (adj), Trying to deceive or cunning, His disingenuous smile didn't fool me;
Disinter (v), Dig up from earth, They disinterred the ancient artifacts;
Dislodge (v), Move or force from place occupied, We tried to dislodge the stuck door;
Dismal (adj), Sad or gloomy, The weather was dismal;
Disparate (adj), Essentially different, The two concepts are disparate;
Disproof (n), Proof to the contrary, They offered disproof of the theory;
Dissemble (v), Hide something in mind, He dissembled his true feelings;
Disseminate (v), Distribute ideas, They disseminated information widely;
Dissent (v), Have different opinion, Several members dissented from the decision;
Dissolution (n), Disintegration or looseness in morals, The dissolution of the marriage was sad;
Distraught (adj), Violently upset in mind, She was distraught with worry;
Divergence (n), Getting farther apart, There is divergence of opinion;
Divestiture (n), Getting rid of or giving up, The company announced divestiture of assets;
Divulge (v), Make known something secret, Don't divulge this information;
Doggerel (n), Trivial poorly constructed verse, The poem was mere doggerel;
Dogmatic (adj), Positive and arbitrary, His dogmatic statements annoyed everyone;
Dolt (n), Stupid fellow, Don't be such a dolt;
Dormant (adj), Inactive but awaiting development, The volcano has been dormant for years;
Dote (v), Show much fondness, Grandparents dote on their grandchildren;
Drawl (n), Slow way of speaking, He spoke with a Southern drawl;
Droll (adj), Jesting or amusing, His droll comments made us laugh;
Drone (n), Person who isn't self-employed, The office drone worked tirelessly;
Drowsiness (n), Feeling sleepy, Drowsiness overcame him;
Dubious (adj), Feeling doubt, I'm dubious about his claims;
Dud (n), Something that fails, The firework was a dud;
Dulcet (adj), Melodious or harmonious, Her dulcet tones were soothing;
Dupe (v), Cheat or make fool of, They duped him into paying;
Duplicity (n), Deliberate deception, His duplicity was exposed;
Duress (n), Threats to compel somebody, He signed under duress;
Dwarf (n), Person much below usual size, The dwarf starred in the play;
Dynamo (n), Generator or energetic person, She's a real dynamo;
Earthenware (n), Dishes made of baked clay, We bought earthenware pots;
Ebullience (n), Exuberance or outburst of feeling, His ebullience was contagious;
Ebullient (adj), Overflowing with enthusiasm, She gave an ebullient performance;
Ecumenical (adj), Representing whole Christian world, The ecumenical council met;
Edacious (adj), Voracious or devouring, His edacious appetite amazed us;
Eddy (n), Circular movement of wind, The boat was caught in an eddy;
Edible (adj), Fit to be eaten, These mushrooms are edible;
Effete (adj), Infertile or worn out, The effete aristocracy declined;
Efficacy (n), Production of desired result, The medicine proved its efficacy;
Effluvia (n), Noxious odor or vapor, Effluvia from the factory polluted the air;
Effrontery (n), Boldness or impudence, He had the effrontery to lie;
Egress (n), Way out or exit, The emergency egress was blocked;
Elaborate (adj), Worked out with much care, They made elaborate plans;
Elegy (n), Lament or melancholy composition, The poet wrote an elegy;
Elicit (v), Draw out, The question elicited no response;
Eloquence (n), Fluent skillful use of language, His eloquence moved the audience;
Emaciate (v), Make thin and weak, The illness emaciated him;
Embellish (v), Make beautiful, She embellished the story;
Embezzle (v), Use wrongly for own benefit, He embezzled company funds;
Emote (v), Stir up or excite, Actors must emote convincingly;
Empirical (adj), Relying on experiment, We need empirical evidence;
Encapsulate (v), Enclose in capsule, This quote encapsulates my philosophy;
Encomium (n), Warm glowing praise, The book received many encomiums;
Encumbrance (n), Burden or things in the way, Debt is a financial encumbrance;
Endearing (adj), Making dear or liked, His endearing smile won hearts;
Endemic (adj), Epidemic or native to area, Malaria is endemic in that region;
Endorse (v), Write name on back or support, I endorse this candidate;
Enduring (adj), Lasting, Their love was enduring;
Enervate (v), Weaken or deprive of strength, The heat enervated us;
Engender (v), Cause or produce, Mistrust engenders conflict;
Engrave (v), Impress deeply, The memory was engraved in her mind;
Engrossing (adj), Taking up all attention, The book was engrossing;
Engulf (v), Swallow up, Flames engulfed the building;
Enigma (n), Something puzzling, He remained an enigma;
Enmity (n), Hatred or being enemy, There was enmity between them;
Ensign (n), Flag or badge, The ship flew its national ensign;
Entangle (v), Put into difficulties, Don't entangle yourself in lies;
Enthral (v), Please greatly or enslave, The performance enthralled the audience;
Entice (v), Tempt or persuade, They enticed customers with discounts;
Entreat (v), Ask earnestly, I entreat you to reconsider;
Enunciate (v), Pronounce words clearly, Please enunciate when speaking;
Enzyme (n), Catalyst, Enzymes aid digestion;
Epicurean (adj), Devoted to pleasure, He lived an epicurean lifestyle;
Epistle (n), Letter, He wrote a long epistle;
Epithet (n), Adjective or descriptive phrase, He hurled epithets at them;
Epitome (n), Brief summary or typical example, She is the epitome of grace;
Equable (adj), Steady or regular, He has an equable temperament;
Equanimity (n), Calmness of temperament, She faced the crisis with equanimity;
Equilibrium (n), State of being balanced, The ecosystem is in equilibrium;
Equipoise (n), Equal distribution of weight, The sculpture achieved perfect equipoise;
Equivocal (adj), Having doubtful meaning, His equivocal answer satisfied no one;
Equivocate (v), Try to deceive by unclear language, Stop equivocating and answer directly;
Eradicate (v), Get rid of completely, We must eradicate poverty;
Erratic (adj), Irregular in behavior, His erratic driving alarmed passengers;
Eschew (v), Avoid, I eschew violence;
Esoteric (adj), Intended only for small circle, The lecture was too esoteric;
Espouse (v), Marry or support, She espoused the cause enthusiastically;
Eulogy (n), Formal praise, He delivered a moving eulogy;
Euphoria (n), State of pleasant excitement, Victory brought euphoria;
Euthanasia (n), Easy and painless death, Some countries allow euthanasia for terminally ill patients;
Evasive (adj), Tending to evade, He gave an evasive answer;
Evince (v), Show clearly or indicate, She evinced great courage;
Evoke (v), Call up or bring out, The music evoked memories;
Excoriation (n), Severe criticism, The film received excoriation from critics;
Exculpate (v), Clear from charge of guilt, New evidence exculpated the defendant;
Exhaustive (adj), Complete or thorough, They conducted an exhaustive search;
Exigency (n), Emergency or urgent situation, The exigency required immediate action;
Exoneration (n), Set free from blame, His exoneration came too late;
Exorbitant (adj), Much too high or great, The hotel charged exorbitant prices;
Expatiate (v), Roam or wander freely, He expatiated on the topic at length;
Expedient (adj), Likely to be useful for purpose, It seemed expedient to agree;
Expiation (n), Ending or expiring, He sought expiation for his sins;
Exploit (v), Develop or use selfishly, They exploited the workers;
Expostulate (v), Argue earnestly to protest, She expostulated with him about his behavior;
Expurgate (v), Remove obscenity or censor, They expurgated offensive passages;
Exscind (v), Cut out or cut away, The surgeon exscinded the tumor;
Extant (adj), Still in existence, Few copies of the book are extant;
Extempore (adv), Without previous preparation, He spoke extempore;
Extenuate (v), Lessen seriousness or partially excuse, Nothing can extenuate his crime;
Extinct (adj), No longer active, The species is extinct;
Extinguish (v), End existence or put out, Firefighters extinguished the blaze;
Extirpate (v), Destroy or cut out, They extirpated the disease;
Extol (v), Praise highly, Critics extolled the performance;
Extort (v), Obtain by threats or violence, Criminals extorted money from businesses;
Extralegal (adj), Outside the law, They took extralegal measures;
Extricable (adj), That can be freed, The problem seemed barely extricable;
Extrovert (n), Cheerful outgoing person, She's a natural extrovert;
Exuberance (n), State of being full of life, His exuberance was infectious;
Facetious (adj), Humorous or jocular, He made a facetious remark;
Facile (adj), Easily done, It was a facile victory;
Fallacious (adj), Based on error, His argument was fallacious;
Falter (v), Waver or move uncertainly, Her voice faltered;
Fatuous (adj), Foolish with self-satisfaction, He made fatuous comments;
Fawn (v), Try to win favor, Don't fawn over the boss;
Feckless (adj), Lacking purpose or careless, His feckless attitude annoyed everyone;
Fecund (adj), Fertile, The fecund soil produced abundant crops;
Feint (n), Pretend attack, The boxer made a feint;
Felicitous (adj), Well chosen or suited, That was a felicitous choice of words;
Felon (n), Person guilty of serious crime, The felon was sentenced to prison;
Ferment (n), Substance or excited state, The city was in ferment;
Ferocity (n), Savage cruelty, The lion attacked with ferocity;
Ferret (v), Discover by searching, She ferreted out the truth;
Fervid (adj), Showing earnest feeling, He made a fervid appeal;
Fervor (n), Warmth of feelings or earnestness, She spoke with fervor;
Fetid (adj), Stinking, The fetid smell was unbearable;
Fetter (v), Shackle or put in chains, They fettered the prisoner;
Feud (n), Bitter quarrel over long period, The families were locked in a feud;
Fidelity (n), Loyalty, He showed fidelity to his principles;
Fidget (v), Move restlessly, Stop fidgeting in your seat;
Figurehead (n), Carved image or powerless leader, The king was merely a figurehead;
Finesse (n), Delicate way of dealing, She handled the situation with finesse;
Finical (adj), Too fussy about food or clothing, Don't be so finical;
Finicky (adj), Too fussy, He's finicky about his food;
Fission (n), Splitting or division, Nuclear fission releases energy;
Fixate (v), Stare at obsessively, Don't fixate on past mistakes;
Flak (n), Criticism or anti-aircraft guns, The proposal drew heavy flak;
Flamboyant (adj), Brightly colored or showy, He wore flamboyant clothes;
Flaunting (v), Show off complacently, She was flaunting her new ring;
Flax (n), Pale yellow or plant, Linen is made from flax;
Fledged (adj), Able to fly or trained, She's a fully fledged doctor;
Fleet (adj), Quick-moving, The fleet runner won easily;
Flinch (v), Draw back or wince, He didn't flinch from danger;
Flop (v), Fail or move clumsily, The play flopped on opening night;
Florid (adj), Very ornamental or red-faced, His florid prose was hard to read;
Flout (v), Reject or go against, She flouted the rules;
Fluke (n), Lucky stroke, His success was just a fluke;
Fluster (v), Make nervous or confused, Don't let the pressure fluster you;
Foible (n), Defect of character, Everyone has their foibles;
Foil (v), Prevent from carrying out, Police foiled the robbery;
Foment (v), Put something warm or incite, They fomented rebellion;
Foolproof (adj), Incapable of failure, We need a foolproof plan;
Foppish (adj), Like man who pays too much attention to clothes, His foppish appearance drew stares;
Forage (n), Food for horses and cattle, The animals searched for forage;
Forbear (v), Refrain from or be patient, Please forbear from commenting;
Forbearance (n), Patience or willingness to wait, His forbearance was admirable;
Ford (n), Shallow place in river to cross, We crossed at the ford;
Forestall (v), Prevent by taking action in advance, They forestalled criticism;
Forfeit (v), Suffer loss of something, He forfeited his right to appeal;
Forge (v), Shape metal or create falsely, They forged ahead despite obstacles;
Forgery (n), Counterfeit, The painting was a forgery;
Forswear (v), Renounce or repudiate, He forswore violence;
Foster (v), Nurture or care for, We must foster creativity;
Fracas (n), Noisy quarrel, A fracas broke out;
Fragile (adj), Easily broken, Handle with care - it's fragile;
Fragrant (adj), Sweet-smelling, The fragrant flowers perfumed the air;
Frantic (adj), Wildly excited, She made a frantic search;
Frenetic (adj), Frantic or frenzied, The pace of work was frenetic;
Fret (v), Worry or irritate, Don't fret about small things;
Fringe (n), Edge or ornamental part, They live on the fringe of society;
Froward (adj), Intractable or stubborn, The froward child refused to obey;
Frugal (adj), Careful or economical, She lived a frugal lifestyle;
Fulmination (n), Bitter protest, His fulminations fell on deaf ears;
Fulsome (adj), Disgusting due to excessiveness, His fulsome praise seemed insincere;
Gainsay (v), Deny or oppose, No one can gainsay the facts;
Garble (v), Make unfair selection from facts, The report garbled the truth;
Garment (n), Article of clothing, She wore a beautiful garment;
Garner (v), Gather and save, He garnered support for his cause;
Garrulity (n), Talkativeness, Her garrulity exhausted listeners;
Garrulous (adj), Too talkative, The garrulous neighbor talked for hours;
Gaucherie (n), Socially awkward behavior, His gaucherie embarrassed everyone;
Germane (adj), Relevant or pertinent, Your comment is not germane;
Gist (n), Point or general sense, Tell me the gist of the story;
Glean (v), Gather facts in small quantities, I gleaned information from various sources;
Glib (adj), Ready and smooth but not sincere, He gave a glib response;
Glimmer (n), Weak or unsteady light, A glimmer of hope remained;
Gloat (v), Look at with selfish delight, Don't gloat over your victory;
Glut (v), Supply too much, The market was glutted with cheap goods;
Gnaw (v), Waste away or bite steadily, Worry gnawed at her;
Goad (n), Something urging person to action, Poverty was a goad to success;
Gorge (v), Eat greedily, They gorged themselves on food;
Gossamer (adj), Soft light delicate, The gossamer fabric floated;
Gouge (n), Tool for cutting grooves, He used a gouge on the wood;
Grandiloquent (adj), Using pompous words, His grandiloquent speech impressed no one;
Grave (adj), Serious requiring consideration, This is a grave matter;
Graze (v), Touch lightly in passing, The bullet grazed his arm;
Gregarious (adj), Liking company, Humans are gregarious by nature;
Grievous (adj), Causing grief or serious, He suffered a grievous injury;
Grovel (v), Crawl or humble oneself, Don't grovel for forgiveness;
Guile (n), Deceit or cunning, He used guile to trick them;
Gullible (adj), Easily deceived, Don't be so gullible;
Gush (v), Burst out suddenly, Water gushed from the pipe;
Gust (n), Sudden burst of wind, A gust blew the door open;
Hack (v), Cut roughly, He hacked through the jungle;
Halcyon (adj), Calm and peaceful, Those were halcyon days;
Hallow (v), Make holy or consecrate, They hallowed the ground;
Harangue (n), Long passionate speech, He delivered a harangue;
Harbinger (n), Something that foretells coming, Spring flowers are harbingers of warm weather;
Harrow (v), Distress or torment, The experience harrowed him;
Haughty (adj), Arrogant or conceited, She gave him a haughty look;
Heed (n), Attention or notice, Pay heed to the warning;
Heinous (adj), Odious crime, It was a heinous act;
Heresy (n), Belief contrary to accepted, He was accused of heresy;
Hermetic (adj), Sealed by fusion, The hermetic seal kept it fresh;
Heterogeneous (adj), Made up of different kinds, The group was heterogeneous;
Hew (v), Make by hard work or cut, They hewed logs for the cabin;
Highbrow (n), Person with superior tastes, He's such a highbrow;
Hirsute (adj), Hairy or shaggy, The hirsute man had a thick beard;
Hoax (n), Mischievous trick, The alien sighting was a hoax;
Hoi Polloi (n), The masses or rabble, He disdained the hoi polloi;
Hollow (adj), Not solid with hole, The tree trunk was hollow;
Holster (n), Leather case for pistol, He drew the gun from his holster;
Homiletics (n), Art of preaching, He studied homiletics in seminary;
Hone (v), Sharpen on stone, He honed his knife;
Hoodwink (v), Trick or mislead, They hoodwinked the investors;
Hospitable (adj), Liking to give hospitality, They were hospitable hosts;
Hubris (n), Arrogant pride, His hubris led to his downfall;
Hush (v), Make or become silent, Hush now and listen;
Husk (n), Worthless outside part, Remove the husk from the corn;
Hypocrisy (n), Falsely appearing good, His hypocrisy was exposed;
Iconoclast (n), Person who attacks popular beliefs, The artist was an iconoclast;
Idiosyncrasy (n), Personal mannerism, Everyone has their idiosyncrasies;
Idolatry (n), Excessive admiration of, His idolatry of celebrities was extreme;
Idyll (n), Carefree episode, Their vacation was an idyll;
Ignoble (adj), Dishonorable or undignified, It was an ignoble act;
Ignominious (adj), Shameful or disgraceful, He suffered an ignominious defeat;
Illicit (adj), Unlawful or forbidden, They engaged in illicit activities;
Imbroglio (n), Complicated embarrassing situation, He found himself in an imbroglio;
Immaculate (adj), Pure or faultless, Her dress was immaculate;
Imminent (adj), Likely to happen soon, Danger was imminent;
Immutable (adj), That cannot be changed, The laws of physics are immutable;
Impair (v), Worsen or diminish value, Smoking impairs your health;
Impassive (adj), Unmoved or showing no passion, His face remained impassive;
Impecunious (adj), Having little or no money, The impecunious student struggled to pay tuition;
Impede (v), Hinder or get in way, Don't impede progress;
Impediment (n), Something that hinders, His stammer was an impediment;
Impending (adj), About to happen, They sensed impending doom;
Imperative (adj), Urgent or essential, It is imperative that we act now;
Imperious (adj), Commanding or arrogant, She spoke in an imperious tone;
Impermeable (adj), That cannot be permeated, The fabric is impermeable to water;
Imperturbable (adj), Calm or not excitable, She remained imperturbable under pressure;
Impervious (adj), Not allowing to pass through, He was impervious to criticism;
Imperviousness (n), Arrogant or commanding quality, His imperviousness to others' feelings was shocking;
Impetuous (adj), Having sudden energy or impulsive, He made an impetuous decision;
Impiety (n), Lack of reverence, His impiety offended them;
Implacable (adj), Incapable of being placated, She was his implacable enemy;
Implicate (v), Show somebody has share, The evidence implicated him;
Implicit (adj), Implied though not expressed, There was implicit trust between them;
Implosion (n), Collapse or bursting inward, The building's implosion was spectacular;
Importune (v), Beg urgently or solicit, Don't importune me for money;
Imprecation (n), Invocation of evil or curse, He uttered imprecations;
Impromptu (adj), Without preparation, She gave an impromptu speech;
Impudent (adj), Rash or indiscreet, His impudent behavior shocked everyone;
Impugned (adj), Challenged to be doubted, His integrity was impugned;
Impute (v), Attribute to cause or ascribe, They imputed motives to him;
Inadvertent (adj), Not paying proper attention, It was an inadvertent error;
Inane (adj), Silly or senseless, He made inane comments;
Inasmuch (conj), Since or because, Inasmuch as you're here, help us;
Incense (v), Make angry, His rudeness incensed her;
Incessant (adj), Often repeated or continual, The incessant noise disturbed us;
Inchoate (adj), Not yet fully formed, The plan was still inchoate;
Incipient (adj), Beginning, The disease was in its incipient stage;
Incise (v), Engrave or make cut, The artist incised the design;
Incite (v), Stir up or rouse, He incited the crowd to violence;
Inclined (adj), Directing mind in certain direction, I'm inclined to agree;
Incongruous (adj), Out of place, His jokes seemed incongruous;
Incorrigibility (n), Cannot be cured or corrected, His incorrigibility frustrated teachers;
Incredulous (adj), Skeptical or unwilling to believe, She gave him an incredulous look;
Inculcate (v), Fix firmly by repetition, Parents inculcate values in children;
Incumbents (n), Official duties, He fulfilled his incumbents;
Incursion (n), Raid or sudden attack, Enemy forces made an incursion;
Indefatigability (n), Not easily exhaustible, His indefatigability was impressive;
Indelible (adj), That cannot be rubbed out, The experience left an indelible mark;
Indigence (n), Poverty, They lived in indigence;
Indigenous (adj), Native, Kangaroos are indigenous to Australia;
Indistinct (adj), Not easily heard or clearly marked, The figure was indistinct in the fog;
Indolence (n), Laziness, His indolence prevented success;
Indomitable (adj), Not easily discouraged, She had an indomitable spirit;
Indulge (v), Gratify or give way to, Don't indulge in self-pity;
Indulgent (adj), Inclined to indulge, She was an indulgent grandmother;
Ineffable (adj), Too great to be described, The beauty was ineffable;
Ineluctable (adj), Certain or inevitable, Death is ineluctable;
Inept (adj), Unskillful or done at wrong time, His inept handling made things worse;
Ineptitude (n), Quality of being unskillful, His ineptitude was obvious;
Inferno (n), Hell or intense fire, The building became an inferno;
Infuriate (v), Fill with fury or rage, His behavior infuriated her;
Infuse (v), Put or pour in, She infused enthusiasm into the team;
Ingenuous (adj), Naive or frank, Her ingenuous smile was charming;
Ingest (v), Take in by swallowing, Don't ingest poison;
Inimical (adj), Harmful or unfriendly, Smoking is inimical to health;
Inimitable (adj), Defying imitation, Her style is inimitable;
Innocuous (adj), Causing no harm, It seemed an innocuous remark;
Inscrutable (adj), Incapable of being understood, His expression was inscrutable;
Insensible (adj), Unconscious or unresponsive, He was insensible to pain;
Insinuate (v), Suggest unpleasantly, Are you insinuating I lied;
Insipid (adj), Without taste or flavor, The soup was insipid;
Insouciant (adj), Unconcerned or carefree, He maintained an insouciant attitude;
Insularity (n), Narrow-mindedness or isolated, His insularity limited his understanding;
Insurrection (n), Rising to open resistance, The insurrection was crushed;
Interdict (v), Prohibit or forbid, The court interdicted the sale;
Interim (n), As an installment or meantime, This is an interim solution;
Intersperse (v), Place here and there, Trees were interspersed among buildings;
Intransigence (n), Unwillingness to compromise, His intransigence blocked progress;
Intransigent (adj), Uncompromising, She was intransigent in negotiations;
Intrepid (adj), Fearless or brave, The intrepid explorer ventured forth;
Introspection (n), Examining own thoughts, Introspection led to self-awareness;
Inundate (v), Flood or cover by overflowing, Requests inundated the office;
Inured (adj), Accustomed or adapted, He was inured to hardship;
Invective (n), Abusive language or curses, He hurled invective at them;
Inveigh (v), Attack verbally or denounce, She inveighed against corruption;
Inveterate (adj), Deep-rooted or long-established, He's an inveterate gambler;
Invincible (adj), Too strong to be defeated, The army seemed invincible;
Involute (adj), Complex, The involute problem confused everyone;
Irascible (adj), Irritable or easily angered, The irascible old man complained constantly;
Irate (adj), Angry, The irate customer demanded a refund;
Ire (n), Anger, His actions provoked her ire;
Irksome (adj), Tiresome or annoying, The delay was irksome;
Irresolute (adj), Hesitating or undecided, Don't be irresolute - choose now;
Irrevocable (adj), Final and unalterable, The decision is irrevocable;
Itinerate (v), Travel from place to place, The preacher itinerated through small towns;
Jabber (v), Talk excitedly, They jabbered on endlessly;
Jibe (v), Make fun of, Don't jibe at others;
Jocular (adj), Meant as joke, He made a jocular remark;
Judicious (adj), Sound in judgment or wise, She made a judicious choice;
Knit (v), Draw together or unite firmly, The community knit together after disaster;
Labyrinthine (adj), To entangle, The labyrinthine passages confused us;
Lachrymose (adj), Causing tears or tearful, The lachrymose movie made everyone cry;
Lackluster (adj), Dull of eyes, His lackluster performance disappointed fans;
Lament (v), Show or feel great sorrow, They lamented the loss;
Lassitude (n), Weariness or tiredness, A feeling of lassitude overcame him;
Latent (adj), Present but not yet active, The disease remained latent;
Laudatory (adj), Expressing or giving praise, The review was laudatory;
Lavish (adj), Giving or producing freely, They received lavish praise;
Legacy (n), Something handed down from ancestors, Education is a priceless legacy;
Levee (n), Formal reception or embankment, The levee held back floodwaters;
Levity (n), Lack of seriousness, This is no time for levity;
Libel (n), Statement that damages reputation, He sued for libel;
Liberality (n), Free giving or generosity, His liberality benefited many;
Libertine (n), Immoral person, He lived like a libertine;
Lien (n), Legal claim until debt repaid, The bank placed a lien on the property;
Limn (v), Paint or portray, The artist limned the scene beautifully;
Limp (adj), Lacking strength, The plant went limp without water;
Lionize (v), Treat as famous person, They lionized the returning hero;
Lithe (adj), Bending or twisting easily, The dancer was lithe and graceful;
Loll (v), Rest or sit lazily, He lolled on the couch;
Lope (v), Move along with long strides, The wolf loped across the field;
Loquacious (adj), Talkative or garrulous, The loquacious host entertained everyone;
Lucubrate (v), Write in scholarly fashion, He lucubrated late into the night;
Luculent (adj), Easily understood or clear, His explanation was luculent;
Lugubrious (adj), Mournful or excessively sad, His lugubrious expression worried us;
Lull (v), Become quiet or less active, The storm lulled briefly;
Lumber (v), Move in clumsy noisy way, The bear lumbered through the forest;
Luminary (n), Star or light-giving body, She's a luminary in her field;
Lurk (v), Be out of view ready to attack, Danger lurks in the shadows;
Lustrous (adj), Being bright or polished, Her lustrous hair shone;
Macabre (adj), Gruesome or suggesting death, The scene was macabre;
Macerate (v), Make or become soft by soaking, Macerate the fruit in wine;
Machination (n), Plot or scheme, His machinations were exposed;
Maladroit (adj), Tactless or clumsy, His maladroit comment offended her;
Malapropism (n), Misuse of word, Her speech was full of malapropisms;
Malevolence (n), Wishing to do evil, His malevolence was evident;
Malign (v), Speak ill of or tell lies, Don't malign innocent people;
Malinger (v), Fake illness to shirk duty, He malingered to avoid work;
Malleable (adj), Easily shaped or adapting, Gold is malleable;
Manacle (n), Chains for hands or feet, They put manacles on the prisoner;
Massacre (n), Cruel killing of large number, The battle ended in massacre;
Matriculation (n), Be admitted as university student, Matriculation begins next week;
Maudlin (adj), Sentimental in silly way, His maudlin tears annoyed everyone;
Maul (v), Hurt by rough handling, The victim was mauled by the dog;
Maverick (n), Rebel or nonconformist, He's a maverick politician;
Mellifluous (adj), Sweetly flowing, Her mellifluous voice soothed listeners;
Mendacity (n), Dishonesty, His mendacity was legendary;
Mendicant (n), Beggar, Mendicants lined the street;
Mercurial (adj), Quick changeable in character, Her mercurial moods were unpredictable;
Meretricious (adj), Attractive on surface but of little value, The meretricious decorations were gaudy;
Mesmerize (v), Hypnotize, The performance mesmerized the audience;
Meticulous (adj), Giving great attention to details, She was meticulous in her work;
Mettle (n), Quality of endurance or courage, The challenge tested his mettle;
Mettlesome (adj), Courageous or high-spirited, The mettlesome horse raced ahead;
Middling (adj), Fairly good but not very good, The meal was middling at best;
Minatory (adj), Menacing or threatening, He gave a minatory glare;
Mince (v), Pronounce affectedly or euphemize, She minced her words carefully;
Misanthrope (n), Person who hates mankind, The old misanthrope avoided everyone;
Mischievous (adj), Harmful or causing mischief, The mischievous child broke the vase;
Miser (n), Person who loves wealth and spends little, The miser hoarded his money;
Misogynist (n), One who hates women, He was accused of being a misogynist;
Moderation (n), Quality of being limited, Moderation is key to health;
Mollify (v), Make calmer or quieter, Nothing could mollify her anger;
Molt (v), Lose hair or feathers before new growing, Birds molt annually;
Morbid (adj), Diseased or unhealthy, He had morbid thoughts;
Morose (adj), Ill-tempered or unsocial, His morose behavior worried friends;
Muffler (n), Cloth worn round neck or silencer, Wrap a muffler around your neck;
Multifarious (adj), Varied or greatly diversified, His multifarious talents impressed everyone;
Mundane (adj), Worldly or commonplace, The task was mundane and boring;
Myriad (adj), Very great number, Myriad stars filled the sky;
Nadir (n), Lowest or weakest point, His career reached its nadir;
Nascent (adj), Coming into existence, The nascent industry showed promise;
Nebulous (adj), Cloud-like or vague, His plans were nebulous;
Negligent (adj), Taking too little care, The negligent driver caused an accident;
Neophyte (n), Person converted to belief, As a neophyte, she had much to learn;
Nexus (n), Connection or link, There's a nexus between poverty and crime;
Nibble (v), Show inclination to accept offer, The fish nibbled at the bait;
Noisome (adj), Offensive or disgusting smell, The noisome odor repelled them;
Nonchalant (adj), Not having interest, He acted nonchalant about the news;
Nonplused (adj), Greatly surprised, She was nonplused by the question;
Nostrum (n), Quack remedy or untested cure, He peddled his nostrum to desperate patients;
Noxious (adj), Harmful, The factory emitted noxious fumes;
Nugatory (adj), Trifling or worthless, His contribution was nugatory;
Obdurate (adj), Hardened and unrepenting, The obdurate criminal showed no remorse;
Obfuscate (v), Darken or make obscure, Don't obfuscate the issue;
Oblivious (adj), Unaware or having no memory, He was oblivious to danger;
Obloquy (n), Abusively detractive language, He heaped obloquy upon them;
Obsequious (adj), Too eager to obey or serve, His obsequious manner was annoying;
Obstreperous (adj), Noisy or loud, The obstreperous crowd disrupted the meeting;
Obtain (v), Be established or customary, Different customs obtain in various countries;
Obtrusive (adj), Projecting or undesirably noticeable, The obtrusive sign blocked the view;
Obtuse (adj), Blunt or stupid, He was obtuse and didn't understand;
Obviate (v), Make unnecessary, This solution obviates the need for repairs;
Occluded (adj), Blocked up, The artery was occluded;
Odious (adj), Repulsive or hateful, His behavior was odious;
Odium (n), Contempt or dislike, He faced public odium;
Odor (n), Smell or reputation, The room had a strange odor;
Officious (adj), Too eager to help or offer advice, The officious clerk irritated customers;
Ominous (adj), Threatening, Dark clouds gave an ominous warning;
Onerous (adj), Needing effort or burdensome, The task was onerous;
Opaqueness (n), Dullness or not allowing light through, The opaqueness of the glass provided privacy;
Opprobrious (adj), Showing scorn or reproach, He made opprobrious remarks;
Ossify (v), Turn to bone or settle rigidly, Don't let your ideas ossify;
Ostensible (adj), Seeming or appearing, His ostensible reason was untrue;
Ostentation (n), Display to obtain admiration, She lived without ostentation;
Ostracism (n), Shut out from society, He faced ostracism after the scandal;
Overhaul (v), Examine thoroughly, The mechanic overhauled the engine;
Overweening (adj), Presumptuously arrogant, His overweening pride annoyed everyone;
Paean (n), Song of praise or triumph, They sang a paean to victory;
Palate (n), Roof of mouth or sense of taste, He has a refined palate;
Palatial (adj), Magnificent, They lived in a palatial mansion;
Palliate (v), Lessen the severity of, Medicine can palliate symptoms;
Palpability (n), Can be felt or understood, The tension had palpability;
Palpitate (v), Tremble or beat rapidly, Her heart palpitated with fear;
Panegyric (n), Formal praise or eulogy, He delivered a panegyric;
Paradigm (n), Model or pattern, This is a new paradigm;
Parenthesis (n), Sentence within another one, The remark was in parenthesis;
Pariah (n), Outcast or rejected person, He became a social pariah;
Parsimonious (adj), Too economical or miserly, The parsimonious man never tipped;
Partisan (adj), One-sided or biased, The newspaper gave partisan coverage;
Patron (n), Regular customer or person who gives support, He was a patron of the arts;
Paucity (n), Scarcity or lacking, There's a paucity of evidence;
Peccadillo (n), Small sin or weakness, Everyone has their peccadillos;
Pedantic (adj), Bookish or showing off learning, His pedantic lectures bored students;
Pedestrian (adj), Commonplace or unremarkable, The writing was pedestrian;
Pellucid (adj), Transparent or easy to understand, The water was pellucid;
Penchant (n), Strong inclination or liking, She has a penchant for chocolate;
Penitent (adj), Feeling or showing regret, The penitent sinner confessed;
Penurious (adj), Poor or stingy, They lived in penurious conditions;
Penury (n), Extreme poverty, The family lived in penury;
Peregrination (n), Traveling about or wandering, His peregrinations took him worldwide;
Peremptory (adj), Urgent or unchallengeable, She gave a peremptory command;
Perfidious (adj), Treacherous or faithless, The perfidious ally betrayed them;
Perfidy (n), Treachery or breaking of faith, His perfidy shocked everyone;
Perfunctory (adj), Done as duty without care, He gave a perfunctory nod;
Perilous (adj), Dangerous, The journey was perilous;
Peripatetic (adj), Wandering, He led a peripatetic lifestyle;
Perish (v), Be destroyed or decay, The food will perish quickly;
Perjury (n), Willful false statement, He was convicted of perjury;
Permeate (v), Spread into every part, The smell permeated the house;
Pernicious (adj), Harmful or injurious, Smoking has pernicious effects;
Perpetrate (v), Be guilty or commit crime, Who perpetrated this crime;
Personable (adj), Pleasing in appearance, He's a personable young man;
Perspicacity (n), Quick judging and understanding, Her perspicacity impressed everyone;
Pertain (v), Belong as part or have reference, This pertains to your case;
Pest (n), Destructive thing or nuisance person, Mosquitoes are pests;
Petrified (adj), Taken away power to act, She was petrified with fear;
Petrify (v), Make hard or rocklike, Time petrified the wood;
Petrous (adj), Like rock or stony, The petrous surface was hard;
Petulant (adj), Unreasonably impatient, The petulant child threw a tantrum;
Philistine (n), Smug ignorant person, Don't be such a philistine;
Phlegmatic (adj), Calm or unemotional, His phlegmatic demeanor never changed;
Picaresque (adj), Involving clever rogues, The picaresque novel was entertaining;
Pied (adj), Of mixed colors, The pied piper wore colorful clothes;
Pinch (v), Be too tight or take between fingers, The shoes pinch my toes;
Pine (v), Waste away through sorrow, She pined for her lost love;
Pious (adj), Dutiful or devoted to religion, He was a pious man;
Piquant (adj), Agreeably pungent or stimulating, The sauce was piquant;
Pique (v), Hurt pride or stir curiosity, His comment piqued her interest;
Pitfall (n), Covered hole as trap or danger, Beware of pitfalls;
Pith (n), Essential part or force, Get to the pith of the matter;
Pivotal (adj), Of great importance, This is a pivotal moment;
Placate (v), Soothe or calm, Nothing could placate her anger;
Plaintive (adj), Mournful or sorrowful, The song was plaintive;
Plaque (n), Flat metal on wall as memorial, A plaque commemorated the event;
Platitude (n), Trite or banal statement, His speech was full of platitudes;
Plea (n), Request, She made an emotional plea;
Plead (v), Address court as advocate, The lawyer pleaded the case;
Plethora (n), Glut or excess, There's a plethora of options;
Pliant (adj), Easily bent or twisted, The pliant material shaped easily;
Plod (v), Continue doing without resting, He plodded through the work;
Pluck (v), Pull feathers off or pick, She plucked the guitar strings;
Plumb (v), Get to root of, Let's plumb the depths of this mystery;
Plummet (v), Fall or plunge steeply, Prices plummeted overnight;
Plunge (v), Move quickly and with force, He plunged into the water;
Poignant (adj), Deeply moving or keen, The story was poignant;
Poncho (n), Large piece of cloth, He wore a poncho in the rain;
Ponderous (adj), Heavy or dull, His ponderous speech dragged on;
Portent (n), Omen or threatening sign, Dark clouds were a portent of storms;
Precarious (adj), Uncertain or dangerous, His position was precarious;
Precepts (n), Rules establishing standards, He lived by moral precepts;
Preclude (v), Prevent or make impossible, This precludes any further action;
Precursory (adj), Preliminary or anticipating, The tremors were precursory to the earthquake;
Predilection (n), Special liking or preference, She has a predilection for mystery novels;
Predominate (v), Have more power than others, Common sense should predominate;
Preen (v), Tidy or show self-satisfaction, Birds preen their feathers;
Premature (adj), Doing something before right time, His celebration was premature;
Preponderance (n), Greatness in number or weight, The preponderance of evidence favors him;
Presage (n), Warning sign, The calm was a presage of the storm;
Presumption (n), Arrogance, His presumption offended everyone;
Preternatural (adj), Not normal or usual, She had preternatural abilities;
Prevalent (adj), Common or widespread, This belief is prevalent;
Prevaricate (v), Equivocate or stray from truth, Stop prevaricating and tell the truth;
Prim (adj), Neat or formal, She had a prim manner;
Pristine (adj), Primitive or pure, The forest was in pristine condition;
Probity (n), Uprightness or principle, He was known for his probity;
Proclivity (n), Inclination, He has a proclivity for gambling;
Procrastination (n), Keeping on putting off, Procrastination is the thief of time;
Prodigal (adj), Wasteful or reckless with money, The prodigal son returned home;
Prodigious (adj), Enormous or wonderful, She had a prodigious talent;
Profane (adj), Worldly or having contempt for god, His language was profane;
Profligacy (n), Shameless immorality, His profligacy scandalized society;
Profligate (adj), Wasteful or extravagant, He led a profligate lifestyle;
Profundity (n), Depth, The profundity of his thought impressed scholars;
Profuse (adj), Abundant or lavish, She offered profuse apologies;
Proliferate (v), Grow by rapid multiplication, Weeds proliferated in the garden;
Prolix (adj), Tiring because too long, His prolix speech exhausted listeners;
Prone (adj), Prostrate or inclined to, He's prone to accidents;
Propagation (n), Increasing number or spreading, The propagation of ideas is important;
Propinquity (n), Nearness in time or place, Their propinquity led to friendship;
Propitiatory (adj), Conciliatory or appeasing, He made a propitiatory gesture;
Propitious (adj), Auspicious or favorable, The weather was propitious;
Prosaic (adj), Everyday or commonplace, His writing was prosaic;
Proscribe (v), Denounce as dangerous, The government proscribed the organization;
Protracted (adj), Prolonged, The negotiations were protracted;
Provident (adj), Frugal or looking to future, It's wise to be provident;
Provisional (adj), Of present time only, This is a provisional agreement;
Provoke (v), Make angry or vex, Don't provoke him;
Prudence (n), Careful forethought, He acted with prudence;
Prudish (adj), Easily shocked or excessively modest, Don't be so prudish;
Prune (v), Cut away dead parts, Prune the bushes in spring;
Pry (v), Inquire too curiously, Don't pry into my affairs;
Pucker (v), Wrinkle, Her brow puckered with concern;
Pugnacious (adj), Fond of fighting, The pugnacious boxer loved combat;
Puissance (n), Strength or power, The knight's puissance was legendary;
Punctilious (adj), Precise or paying attention to trivialities, She was punctilious about etiquette;
Pundit (n), Authority on subject, The political pundit analyzed the election;
Pungency (n), Sharpness or stinging quality, The pungency of the spice made eyes water;
Purvey (v), Provide or supply, They purveyed fine goods;
Pusillanimous (adj), Cowardly or craven, His pusillanimous behavior disappointed everyone;
Putrefaction (n), Becoming rotten, Putrefaction set in quickly;
Pyre (n), Large pile of wood for burning, They built a funeral pyre;
Quack (n), Person dishonestly claiming something, The quack doctor was exposed;
Quaff (v), Drink deeply, They quaffed ale at the tavern;
Quail (v), Lose courage or turn frightened, He quailed before the enemy;
Qualm (n), Feeling of doubt, She had qualms about the decision;
Quandary (n), State of doubt or perplexity, I'm in a quandary about what to do;
Quell (v), Suppress or subdue, The army quelled the rebellion;
Quibble (v), Try to avoid by sophistication, Don't quibble over minor details;
Quiescence (n), State of being passive, The volcano's quiescence worried scientists;
Quiescent (adj), At rest or dormant, The disease remained quiescent;
Quirk (n), Habit peculiar to somebody, Everyone has their quirks;
Quixotic (adj), Generous or unselfish, His quixotic gesture surprised everyone;
Quotidian (adj), Banal or everyday, Life consisted of quotidian tasks;
Rabble (n), Mob or lower classes, The rabble rioted in streets;
Raconteur (n), Person who tells anecdotes, He was a gifted raconteur;
Raffish (adj), Low or base, His raffish appearance disturbed them;
Ramify (v), Be divided or branch out, The consequences ramified widely;
Rancorous (adj), Feeling bitterness or spitefulness, The debate became rancorous;
Rant (v), Use extravagant language, He ranted about the injustice;
Rapacious (adj), Greedy especially for money, The rapacious landlord raised rents;
Rarefy (v), Make thin or purify, The air rarefied at high altitude;
Rave (v), Act with excessive enthusiasm, Critics raved about the performance;
Reactionary (adj), Opposing progress, He held reactionary views;
Rebuff (n), Snub or rejection, She gave him a cold rebuff;
Recalcitrant (adj), Disobedient, The recalcitrant child refused to obey;
Recant (v), Take back as false, He refused to recant his statement;
Recast (v), Cast or fashion anew, They recast the play;
Recidivism (n), Relapse into criminal behavior, The prison has high recidivism rates;
Reciprocity (n), Granting privileges in return for similar, Trade agreements require reciprocity;
Recitals (n), Number of performances of music, She gave piano recitals;
Recluse (n), Person who lives alone, He became a recluse;
Recompense (n), Make payment or reward, He received recompense for damages;
Reconcile (v), Settle quarrel or restore peace, They reconciled after the fight;
Recondite (adj), Little known or abstruse, The subject was recondite;
Recreancy (n), Cowardice or giving up, His recreancy shamed his family;
Recuperate (v), Become strong after illness, He's recuperating from surgery;
Redeem (v), Get back by payment, She redeemed her reputation;
Redoubtable (adj), Formidable or causing fear, The redoubtable warrior was feared;
Refine (v), Make or become pure, Refine your argument;
Refractory (adj), Stubborn or unmanageable, The refractory student caused problems;
Refulgent (adj), Shining or brilliant, The refulgent stars lit the sky;
Regale (v), Delight or entertain, He regaled us with stories;
Regicide (n), Crime of killing king, The conspirators committed regicide;
Reiterate (v), Say or do again several times, Let me reiterate my point;
Rejuvenation (n), Becoming young again, The spa promised rejuvenation;
Relapse (v), Fall back again, He relapsed into old habits;
Remonstrate (v), Protest or object, She remonstrated with him;
Render (v), Deliver or provide, Please render your decision;
Renovate (v), Restore to better condition, They renovated the old house;
Renowned (adj), Celebrated or famous, She's a renowned scientist;
Repast (n), Meal, They enjoyed a hearty repast;
Repel (v), Refuse to accept or cause dislike, His manner repelled visitors;
Repine (v), Be discontented with, Don't repine at your fate;
Reproach (v), Scold or upbraid, She reproached him for lying;
Reprobate (n), Person hardened in sin, The old reprobate reformed;
Repudiate (v), Disown or refuse to accept, He repudiated the allegations;
Repulsive (adj), Causing feeling of disgust, The sight was repulsive;
Requite (v), Repay or give in return, She requited his kindness;
Rescind (v), Repeal or cancel, The company rescinded the policy;
Resigned (adj), Unresisting or submissive, He was resigned to his fate;
Resilience (n), Quality of quickly recovering, Her resilience helped her bounce back;
Resort (v), Frequently visit, They resort to the beach in summer;
Restive (adj), Refusing to move or be controlled, The restive horse bucked;
Resuscitation (n), Coming back to consciousness, CPR saved him through resuscitation;
Retard (v), Check or hinder, Bad weather retarded progress;
Reticent (adj), Reserved or not talkative, He was reticent about his past;
Revere (v), Have deep respect for, They revered their ancestors;
Reverent (adj), Feeling deep respect, The crowd was reverent;
Riddle (n), Puzzling person or thing, His behavior is a riddle;
Rift (n), Split or dissension, A rift developed in their friendship;
Rivet (v), Fix or secure, The story riveted our attention;
Roll Call (n), Calling of names, They conducted roll call;
Rotund (adj), Plump and round, The rotund gentleman laughed heartily;
Ruffian (n), Violent cruel man, The ruffians attacked innocent people;
Rumple (v), Make rough or wrinkled, Don't rumple the sheets;
Sagacious (adj), Having sound judgment or wise, The sagacious leader made wise decisions;
Salacious (adj), Obscene or lustful, The tabloid printed salacious gossip;
Salubrious (adj), Healthful, The mountain air is salubrious;
Salutary (adj), Remedial or causing improvement, The experience had a salutary effect;
Sanctimony (n), Self-righteousness or false piety, His sanctimony annoyed everyone;
Sanction (n), Approval or penalty, The government imposed sanctions;
Sanguine (adj), Cheerful or optimistic, She remained sanguine despite setbacks;
Sanity (n), Health of mind or soundness, He questioned her sanity;
Sash (n), Long strip worn round waist, She wore a silk sash;
Satiate (v), Satisfy fully, The meal satiated our hunger;
Saturnine (adj), Gloomy or sullen, His saturnine expression never changed;
Savant (n), Person of great learning, He was a mathematical savant;
Savor (v), Taste something or enjoy, Savor each moment;
Sawdust (n), Tiny bits of wood, The floor was covered with sawdust;
Scabbard (n), Sheath for blade, He returned the sword to its scabbard;
Scent (n), Smell especially pleasant, The roses had a lovely scent;
Scorch (v), Become discolored or burn, The sun scorched the grass;
Scribble (v), Write hastily, She scribbled a note;
Scurvy (adj), Mean or contemptible, That was a scurvy trick;
Secular (adj), Material not spiritual, He led a secular life;
Sedulous (adj), Persevering or diligent, Her sedulous efforts paid off;
Seminal (adj), Like seed or originative, This was a seminal work;
Sententious (adj), Short and pithy, His sententious remarks were memorable;
Sequence (n), Succession or connected line, The sequence of events was clear;
Sere (v), Make hard and without feeling, Years of hardship sered his heart;
Sermon (n), Reproving person for faults, The priest delivered a stern sermon;
Serrated (adj), Having toothed edge, The knife had a serrated blade;
Serration (n), Having toothed edge, The leaf's serration was distinctive;
Servile (adj), Like slave or lacking independence, His servile manner was degrading;
Sever (v), Break off or cut, They severed all ties;
Severance (n), Severing or separation, He received severance pay;
Shallow (adj), Little depth or not earnest, The pool is shallow;
Shard (n), Piece of broken earthenware, She found pottery shards;
Sheath (n), Cover for blade, Put the knife in its sheath;
Shrewd (adj), Astute or showing sound judgment, She made a shrewd investment;
Shrill (adj), Sharp or piercing, The whistle was shrill;
Shun (v), Keep away from or avoid, They shunned him after the scandal;
Shunt (v), Send from one track to another, The train was shunted to another line;
Sidestep (v), Step to side or avoid, He sidestepped the question;
Simper (v), Give silly self-conscious smile, She simpered at the compliment;
Sinuous (adj), Winding or serpentine, The river followed a sinuous path;
Skiff (n), Small boat, They rowed the skiff to shore;
Skit (n), Short humorous writing, They performed a comedy skit;
Slack (adj), Sluggish or not tight, Business was slack;
Slake (v), Assuage or satisfy, Water slaked his thirst;
Slate (n), Blue-grey stone or propose, He was slated for promotion;
Sluggard (n), Lazy slow-moving person, Don't be such a sluggard;
Slur (v), Join sounds indistinctly, He slurred his words;
Smolder (v), Burn slowly without flame, The fire smoldered for hours;
Snare (n), Trap, They set a snare for rabbits;
Snub (v), Treat with contempt, She snubbed him at the party;
Soar (v), Rise or fly high, The eagle soared overhead;
Sober (adj), Self-controlled or not drunk, He remained sober throughout;
Sobriety (n), Quality of being sober, Sobriety is important when driving;
Sodden (adj), Soaked or saturated, The sodden ground squelched;
Soggy (adj), Heavy with water, The bread was soggy;
Solvent (adj), Of power of forming solution, The company is financially solvent;
Somatic (adj), Of the body, The symptoms were somatic;
Soot (n), Black powder in smoke, Soot covered the chimney;
Sophisticated (adj), Complex or refined, She had sophisticated tastes;
Sophistry (n), Fallacious reasoning or faulty logic, His argument was pure sophistry;
Sophomoric (adj), Self-assured though immature, His sophomoric behavior embarrassed us;
Soporific (adj), Producing sleep, The lecture was soporific;
Sordid (adj), Wretched or contemptible, The details were sordid;
Spear (n), Weapon with metal point, He threw the spear;
Specious (adj), Illogical or questionable, Her reasoning was specious;
Splenetic (adj), Bad-tempered or irritable, The splenetic old man complained constantly;
Splice (v), Join two ends, They spliced the rope;
Sponge (n), Porous rubber for washing, Clean it with a sponge;
Spurious (adj), False or counterfeit, The document was spurious;
Spurn (v), Have nothing to do with or reject, She spurned his advances;
Squalid (adj), Foul or filthy, They lived in squalid conditions;
Squander (v), Spend wastefully, Don't squander your inheritance;
Squat (v), Crouch or settle without permission, They squatted on vacant land;
Stanch (v), Stop flow of fluid, The bandage stanched the bleeding;
Steeply (adv), Rising or falling sharply, Prices rose steeply;
Stentorian (adj), Extremely loud and powerful, His stentorian voice boomed;
Stickler (n), Person who insists on importance, She's a stickler for punctuality;
Stigma (n), Mark of shame or disgrace, There's a stigma attached to mental illness;
Stigmatize (v), Describe somebody scornfully, Don't stigmatize the victims;
Sting (n), Something sharp or wound, The bee's sting hurt;
Stingy (adj), Spending unwillingly, He was stingy with compliments;
Stint (v), Be thrifty or set limits, Don't stint on quality;
Stipple (v), Paint with dots, The artist stippled the canvas;
Stipulate (v), State as necessary condition, The contract stipulates payment terms;
Stolid (adj), Showing no emotion, His stolid expression revealed nothing;
Stray (v), Wander or lose one's way, The dog strayed from home;
Streak (n), Long thin line or move fast, A streak of lightning lit the sky;
Striated (adj), Striped or grooved, The rock was striated;
Stride (v), Walk with long steps, He strode confidently forward;
Strut (n), Supporting bar, The bridge has steel struts;
Stygian (adj), Dark or gloomy, The stygian depths were frightening;
Stymie (v), Hinder or block, Bad weather stymied our plans;
Subdue (v), Overcome or bring under control, They subdued the attacker;
Sublime (adj), Extreme or astounding, The view was sublime;
Submerge (v), Put under water or sink, The submarine submerged;
Suborn (v), Induce by bribery to commit perjury, They tried to suborn witnesses;
Subpoena (n), Written order requiring court appearance, He received a subpoena;
Substantiation (n), Giving facts to support statement, We need substantiation of your claims;
Subsume (v), Include under rule, This case is subsumed under that law;
Succor (n), Assistance or relief in distress, They provided succor to refugees;
Suffice (v), Be enough, This will suffice for now;
Suffocate (v), Have difficulty breathing, The smoke almost suffocated them;
Sullied (adj), Stained or discredited, His reputation was sullied;
Summarily (adv), Briefly or without delay, The case was summarily dismissed;
Sumptuous (adj), Magnificent or luxurious, They enjoyed a sumptuous feast;
Sundry (adj), Various or miscellaneous, She bought sundry items;
Supercilious (adj), Disdainful or haughty, He gave a supercilious smile;
Superfluous (adj), More than needed, Remove superfluous words;
Superimpose (v), Put on top, They superimposed one image on another;
Supersede (v), Take place of, New technology superseded the old;
Supine (adj), Lying on back or passive, He remained supine throughout;
Suppliant (adj), Asking humbly or beseeching, She made a suppliant gesture;
Supplicate (v), Make humble petition, They supplicated for mercy;
Suppress (v), Prevent from being known, They tried to suppress the truth;
Surcharge (n), Additional load or charge, There's a surcharge for late payment;
Surfeit (n), Satiate or excess, A surfeit of food made them ill;
Susceptibility (n), Sensitiveness, Her susceptibility to colds worried her;
Swerve (v), Change direction suddenly, The car swerved to avoid collision;
Sycophant (n), Person who flatters the powerful, He surrounded himself with sycophants;
Synopsis (n), Summary or outline, Give me a synopsis of the book;
Taciturn (adj), Not talkative or silent, The taciturn man rarely spoke;
Tadpole (n), Form of frog when it leaves egg, Tadpoles swim in the pond;
Talon (n), Claw of bird of prey, The eagle's talons gripped its prey;
Tamp (v), Tap or drive down by light blows, Tamp down the soil;
Tamper (v), Interfere with, Don't tamper with the evidence;
Tangential (adj), Suddenly changeable or peripheral, His comments were tangential;
Tarnished (adj), Lost brightness, The silver had tarnished;
Tassel (n), Bunch of threads, The curtain had decorative tassels;
Taunt (n), Contemptuous reproach or hurtful remark, The bully's taunts hurt him;
Taut (adj), Tightly stretched, Pull the rope taut;
Tautology (n), Repetition or redundancy, Saying "free gift" is a tautology;
Tawdry (adj), Cheap or showy, She wore tawdry jewelry;
Teetotal (adj), Opposed to alcohol, He's teetotal and never drinks;
Temerity (n), Boldness or intrepidness, He had the temerity to argue;
Temperance (n), Abstinence from alcohol or moderation, The movement promoted temperance;
Temperate (adj), Showing self-control, She gave a temperate response;
Tenacity (n), Firmness or persistence, His tenacity helped him succeed;
Tenuous (adj), Insubstantial or weak, The connection was tenuous;
Tepid (adj), Lukewarm, The bathwater was tepid;
Terse (adj), Brief and to point, His reply was terse;
Testiness (n), Witness or evidence, His testiness annoyed everyone;
Thrift (n), Care or economy, Thrift is a virtue;
Thwart (v), Obstruct or frustrate, They thwarted our plans;
Timid (adj), Shy or easily frightened, The timid child hid behind her mother;
Timorous (adj), Fearful or afraid, The timorous rabbit ran away;
Toady (n), Obsequious flatterer, He was the boss's toady;
Tonic (n), Something giving strength, Fresh air is a tonic;
Topple (v), Be unsteady and overturn, The statue toppled over;
Torment (n), Severe pain or suffering, The disease caused torment;
Torpid (adj), Sleeping or lethargic, The bear was torpid in winter;
Torque (n), Twisting force causing rotation, The engine produces high torque;
Tortuous (adj), Devious or not straightforward, The path was tortuous;
Tout (n), Person who worries others to buy, The tout hassled tourists;
Tractable (adj), Easily controlled or guided, The tractable student followed directions;
Transgress (v), Break or go beyond limit, Don't transgress the rules;
Transient (adj), Temporary or fleeting, Beauty is transient;
Transitory (adj), Brief or short-lived, Fame is transitory;
Travesty (n), Parody or imitation, The trial was a travesty of justice;
Trenchant (adj), Forceful or incisive, She made trenchant criticisms;
Trepidation (n), Alarm or excited state, He approached with trepidation;
Trickle (v), Flow in drops, Water trickled from the tap;
Trifling (adj), Unimportant or trivial, It's a trifling matter;
Trite (adj), Not new or overused, His jokes were trite;
Truce (n), Stop of fighting for time, They called a truce;
Truculence (n), Aggressiveness or ferocity, His truculence intimidated others;
Trudge (v), Walk heavily, They trudged through snow;
Turbid (adj), Muddy or having sediment stirred, The river water was turbid;
Turbulence (n), Being uncontrolled or violent, The plane hit turbulence;
Turgid (adj), Excessively ornate or swollen, His turgid prose was unreadable;
Turmoil (n), Trouble or disturbance, The country was in turmoil;
Turpitude (n), Wickedness or shamefulness, His moral turpitude was shocking;
Turquoise (n), Greenish-blue precious stone, She wore a turquoise necklace;
Tyro (n), Beginner or novice, As a tyro, he made many mistakes;
Ubiquitous (adj), Present everywhere, Smartphones are ubiquitous today;
Ulterior (adj), Situated beyond or hidden, He had ulterior motives;
Umbrage (n), Offense or resentment, She took umbrage at his remarks;
Uncouth (adj), Rough or awkward, His uncouth manners embarrassed everyone;
Underbid (v), Make lower bid than somebody, They underbid their competitors;
Undermine (v), Weaken gradually at base, Criticism undermined his confidence;
Undulate (v), Move in wavelike fashion, The fields undulated in the wind;
Unearth (v), Discover and bring to light, Archaeologists unearthed ancient ruins;
Unencumbered (adj), Easy-going or free, She felt unencumbered after retirement;
Unfeigned (adj), Not pretended or sincere, His joy was unfeigned;
Unscathed (adj), Unharmed or unhurt, He emerged unscathed from the accident;
Untoward (adj), Unfortunate or inconvenient, Nothing untoward happened;
Upbraid (v), Scold or reproach, He upbraided the team;
Urbane (adj), Elegant refined in manners, He was urbane;
Vacillation (n), Being uncertain, His vacillation was annoying;
Vagary (n), Strange act or idea, The vagaries of fashion;
Vain (adj), Without use, It was a vain attempt;
Valiant (adj), Brave, A valiant soldier;
Valorous (adj), Brave, The valorous knight;
Vanquish (v), Conquer, He vanquished his enemies;
Veer (v), Change direction, The car veered off the road;
Venal (adj), Ready to do something dishonest, A venal politician;
Veneer (n), Surface appearance covering nature, A veneer of politeness;
Veneration (n), Regard with deep respect, He was held in veneration;
Veracity (n), Truth, We questioned the veracity of the story;
Verdant (adj), Fresh and green, Verdant fields;
Verisimilitude (n), Appearing true or real, The novel lacked verisimilitude;
Veritable (adj), Real rightly named, A veritable feast;
Verve (n), Spirit vigor enthusiasm, She performed with verve;
Vestige (n), Trace or sign, A vestige of the past;
Vex (v), Annoy distress, Don't vex the dog;
Vigilance (n), Watchfulness, Constant vigilance is required;
Vigilant (adj), Watchful, Be vigilant against fraud;
Vigorous (adj), Strong energetic, Vigorous exercise;
Vilify (v), Slander, Don't vilify your opponents;
Vindictive (adj), Having desire to revenge, A vindictive person;
Virago (n), Loud domineering woman, She was portrayed as a virago;
Visceral (adj), Of internal organs, A visceral reaction;
Viscous (adj), Sticky, Viscous liquid;
Vitiate (v), Lower quality, This error vitiates the contract;
Vituperate (v), Curse abuse, He vituperated the driver;
Vivacious (adj), Lively, A vivacious personality;
Volatile (adj), Changeable, A volatile market;
Volubility (n), Fluency verbosity, Her volubility was surprising;
Voluble (adj), Fluent, A voluble speaker;
Waffle (v), Talk vaguely, Stop waffling and decide;
Waft (v), Carry lightly, A scent wafted in;
Wag (n), Merry person, He's a bit of a wag;
Warmonger (n), Person stirs up war, He was accused of being a warmonger;
Warrant (n), Authority order, A warrant for arrest;
Wean (v), Turn away from habit, Wean the baby;
Weigh (v), Measure heaviness, Weigh the options;
Welter (n), Turmoil, A welter of confusion;
Wend (v), Go proceed, Wend your way home;
Whimsical (adj), Odd fanciful, A whimsical idea;
Wince (v), Show pain, He winced in pain;
Woo (v), Try to win, He wooed her with flowers;
Writ (n), Written order, A writ of habeas corpus;
Yarn (n), Tale story fibers, Spinning yarn;`;

// Helper to parse the raw vocabulary string into objects
const parseVocabulary = (): VocabularyWord[] => {
  return rawVocabulary.split('\n').filter(line => line.trim().length > 0).map((line, index) => {
    // Regex matches: Word (POS), Definition, Sentence;
    // Group 1: Word
    // Group 2: POS (optional)
    // Group 3: Definition
    // Group 4: Sentence (optional)
    const regex = /^([^,(]+)(?:\s*\(([^)]+)\))?\s*,?\s*([^,;]+)(?:[;,]\s*(.*))?$/;
    const match = line.match(regex);

    if (match) {
        const word = match[1].trim();
        const pos = match[2] ? match[2].trim() : 'unknown';
        const definition = match[3] ? match[3].trim() : 'No definition provided';
        const example = match[4] ? match[4].trim() : `Example sentence for ${word}.`;
        const unitNum = Math.floor(index / 10) + 1;

        return {
            id: (index + 1).toString(),
            word: word,
            definition: definition,
            part_of_speech: pos,
            example_sentence: example,
            synonyms: [],
            difficulty_level: Math.ceil(unitNum / 30) || 1,
            unit_number: unitNum
        };
    } else {
        // Fallback for lines that might fail regex
        const parts = line.split(',');
        const word = parts[0]?.trim() || `Word-${index}`;
        return {
            id: (index + 1).toString(),
            word: word,
            definition: parts[1]?.trim() || 'Definition unavailable',
            part_of_speech: 'unknown',
            example_sentence: parts[2]?.trim() || `Example for ${word}`,
            synonyms: [],
            difficulty_level: 1,
            unit_number: Math.floor(index / 10) + 1
        };
    }
  });
};

export const SEED_VOCABULARY: VocabularyWord[] = parseVocabulary();

export const getWordByGlobalIndex = (index: number): VocabularyWord => {
  if (index < SEED_VOCABULARY.length) {
    return SEED_VOCABULARY[index];
  }
  // Safe fallback if index exceeds array (though with 1161 items, unlikely for current scope)
  return SEED_VOCABULARY[SEED_VOCABULARY.length - 1];
};

export const generateUnits = (): Unit[] => {
  const units: Unit[] = [];
  // 120 units covers 1200 words (10 per unit), sufficient for 1161 words
  const TOTAL_UNITS = 120; 

  for (let u = 1; u <= TOTAL_UNITS; u++) {
    const lessons: LessonNode[] = [];
    
    // Generate 10 Lessons (Learning) + 1 Test (Retention Check)
    for (let l = 1; l <= 11; l++) {
      let type: 'intro' | 'practice' | 'test' = 'practice';
      if (l === 11) type = 'test';
      else type = 'intro'; 

      lessons.push({
        id: `unit-${u}-lesson-${l}`,
        unitId: u,
        lessonNumber: l,
        type: type,
        isLocked: u === 1 && l === 1 ? false : true, 
        completed: false
      });
    }

    units.push({
      id: u,
      title: `Unit ${u}: ${u <= 30 ? 'Foundations' : u <= 60 ? 'Intermediate' : u <= 90 ? 'Advanced' : 'Mastery'}`,
      lessons,
      isLocked: u > 1
    });
  }
  return units;
};

// Helper to shuffle array (Exported for use in Learn.tsx fallback)
export const shuffle = <T>(array: T[]): T[] => [...array].sort(() => Math.random() - 0.5);

// New Helper to get words for a lesson to feed into AI
export const getWordsForLesson = (lessonId: string): VocabularyWord[] => {
  const parts = lessonId.split('-'); 
  const unitNum = parseInt(parts[1]);
  const lessonNum = parseInt(parts[3]);
  const words: VocabularyWord[] = [];

  // If Unit Test, get all words from current unit
  if (lessonNum === 11) {
    const currentUnitStartIdx = (unitNum - 1) * 10;
    for (let i = 0; i < 10; i++) {
      words.push(getWordByGlobalIndex(currentUnitStartIdx + i));
    }
  } else {
    // For standard lessons, get the new word + review words
    const newWordIndex = ((unitNum - 1) * 10) + (lessonNum - 1);
    words.push(getWordByGlobalIndex(newWordIndex));

    for (let i = 1; i < lessonNum && i <= 3; i++) {
       const reviewIdx = ((unitNum - 1) * 10) + (i - 1);
       words.push(getWordByGlobalIndex(reviewIdx));
    }
  }
  
  return words;
}

export const generateExercisesForLesson = (lessonId: string): Exercise[] => {
  const parts = lessonId.split('-'); 
  const unitNum = parseInt(parts[1]);
  const lessonNum = parseInt(parts[3]);
  const exercises: Exercise[] = [];

  if (lessonNum === 11) {
    const currentUnitStartIdx = (unitNum - 1) * 10;
    const currentUnitWords = Array.from({ length: 10 }, (_, i) => getWordByGlobalIndex(currentUnitStartIdx + i));
    
    currentUnitWords.forEach(word => {
      const distractors = currentUnitWords.filter(w => w.id !== word.id).map(w => w.definition);
      exercises.push({
        id: `test-${word.id}-${Date.now()}`,
        type: 'mcq',
        word: word,
        questionText: `Select the correct definition for: ${word.word}`,
        options: shuffle([word.definition, ...shuffle(distractors).slice(0, 3)]),
        correctAnswer: word.definition
      });
    });
    return shuffle(exercises);
  }

  const newWordIndex = ((unitNum - 1) * 10) + (lessonNum - 1);
  const newWord = getWordByGlobalIndex(newWordIndex);

  exercises.push({
    id: `new-scaffold-${newWord.id}`,
    type: 'scaffolded',
    word: newWord,
    correctAnswer: 'understood'
  });

  return exercises;
};